### ISSUE TITLE
Using the new event based parse runner?

### ISSUE THREAD

**Issue by fge** [uscexp/grappa.extension#10]
Hello,

Since I have no contact information other than the issue here, this is something of a mail, if you wish.

I see that you use the RecoveringParseRunner so that you can access the parse tree; this means that you use the `@BuildParseTree` annotation.

Now, the thing is, I have developed an event-based parse runner, using an EventBus from Guava, which allows me to build whatever I need, in fact, including a parse tree.

Originally developed under 2.0.x, a backport can be found [here](https://github.com/fge/grappa-tracer-backport). This package contains already an implementation to allow the production of trace files to use with [the GUI "debugger"](https://github.com/fge/grappa-debugger).

Do you think you can make use of that event-based parse runner to implement this extension?

(if you want to continue this conversation by mail, see my profile; my mail address is mentioned)

**Comment by uscexp** [comment]
Implemented! New release use grappa v2.0.4.
